### ISSUE TITLE
Comment count for post

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#126]
This is a rather high priority thing but would be nice to have visible in my posts. How would I go about getting the comment count for a given post? I'd like to add this to the Comments link at the top of my posts. Thx in advance! Great add-on so far!  :D

**Comment by JohnathonKoster** [comment]
This can be achieved currently with the `{{ meerkat:count }}` Antlers tag. This tag supports the same `filter` parameter as `responses` (so that both can be supplied to have a count that agrees).

I understand that this has performance implications, and is not very "fun" to work with, and will work on some options to make this better in the next update (probably something like `{{ meerakt:current_count }}` that will use a cached value from whatever was resolved from the on page responses). It also looks like I need to include some guides and documentation on some of these lesser-known features :)

**Comment by jeffwhitfield** [comment]
Well, with caching, performance is less of a problem. One of the things I'll be experimenting with is a fully cached page with a comment form on it. That'll require an Ajax driven form (via Vue, Alpine JS, etc.) so I'll be working on that. Once that works then comment counts will just be cached on the page and won't cause a performance hit at all.  :)

**Comment by JohnathonKoster** [comment]
Good evening!

This has been documented at https://meerkatcomments.com/docs/display-comment-counts

Version 2.1.13-beta2 also adds a format_number parameter so we can all now customize how large comment counts are formatted (decimal separator, thousands separator, etc.):

<p>You have {{ meerkat:count  format_number="1|,|," }} comment(s).</p>
